// Shared patient data used across patients list and patient profile pages

export const patientsData = [
  {
    id: "P-1001",
    name: "Emily Johnson",
    phone: "+1 234-567-8900",
    email: "emily.j@example.com",
    dob: "Jan 15, 1992 (32 years)",
    address: "123 Oak Avenue, Suite 400\nNew York, NY 10001",
    lastVisit: "Mar 15, 2024",
    nextAppt: "Mar 28, 2024",
    status: "Active",
    avatar: "EJ",
    color: "from-blue-500 to-cyan-500",
    visits: 12,
    registeredSince: "Jan 2023",
    outstanding: "$450",
    lastXRay: "Feb 2024",
    insurance: "Delta",
    allergies: [
      { name: "Penicillin", severity: "destructive" },
      { name: "Latex", severity: "warning" },
      { name: "Aspirin (mild)", severity: "outline" },
    ],
    conditions: [
      { name: "Hypertension", diagnosed: "2018", status: "Controlled", statusColor: "bg-amber-50 text-amber-700 border-amber-200" },
      { name: "Type 2 Diabetes", diagnosed: "2020", status: "Managed", statusColor: "bg-emerald-50 text-emerald-700 border-emerald-200" },
    ],
    medications: [
      { name: "Lisinopril 10mg", dosage: "1 tablet daily (Blood Pressure)", color: "bg-purple-50 text-purple-600" },
      { name: "Metformin 500mg", dosage: "Twice daily with meals (Diabetes)", color: "bg-blue-50 text-blue-600" },
    ],
    visitHistory: [
      { date: "Mar 15, 2024", treatment: "Root Canal Treatment", doctor: "Dr. Smith", notes: "Completed successful RCT on tooth #14. Prescribed Amoxicillin 500mg x 7 days.", tooth: "#14" },
      { date: "Feb 20, 2024", treatment: "Panoramic X-Ray & Examination", doctor: "Dr. Adams", notes: "Patient reported sensitivity to hot/cold. Full mouth X-rays taken. Identified cavity on #14.", tooth: "Full" },
      { date: "Jan 05, 2024", treatment: "Routine Cleaning & Polishing", doctor: "Dr. Lee", notes: "Standard prophylaxis. Gum health excellent. Next cleaning in 6 months.", tooth: "All" },
    ],
    invoices: [
      { id: "INV-2024-001", date: "Mar 15, 2024", amount: "$300.00", status: "Overdue", treatment: "Root Canal Treatment" },
      { id: "INV-2024-002", date: "Mar 20, 2024", amount: "$150.00", status: "Due in 5 days", treatment: "Panoramic X-Ray & Exam" },
    ],
  },
  {
    id: "P-1002",
    name: "Marcus Williams",
    phone: "+1 234-567-8901",
    email: "marcus.w@example.com",
    dob: "Jun 22, 1988 (35 years)",
    address: "456 Elm Street, Apt 12\nBrooklyn, NY 11201",
    lastVisit: "Feb 20, 2024",
    nextAppt: "Mar 28, 2024",
    status: "Active",
    avatar: "MW",
    color: "from-purple-500 to-pink-500",
    visits: 8,
    registeredSince: "Mar 2023",
    outstanding: "$850",
    lastXRay: "Jan 2024",
    insurance: "Cigna",
    allergies: [
      { name: "Codeine", severity: "destructive" },
    ],
    conditions: [
      { name: "Asthma", diagnosed: "2005", status: "Controlled", statusColor: "bg-amber-50 text-amber-700 border-amber-200" },
    ],
    medications: [
      { name: "Albuterol Inhaler", dosage: "As needed (Asthma)", color: "bg-blue-50 text-blue-600" },
    ],
    visitHistory: [
      { date: "Feb 20, 2024", treatment: "Root Canal Therapy", doctor: "Dr. Smith", notes: "Started RCT on tooth #36. Patient tolerated procedure well.", tooth: "#36" },
      { date: "Jan 15, 2024", treatment: "Dental Examination", doctor: "Dr. Adams", notes: "Identified deep cavity on #36 requiring root canal.", tooth: "#36" },
    ],
    invoices: [
      { id: "INV-2024-003", date: "Feb 20, 2024", amount: "$850.00", status: "Pending", treatment: "Root Canal Therapy" },
    ],
  },
  {
    id: "P-1003",
    name: "Sarah Chen",
    phone: "+1 234-567-8902",
    email: "sarah.c@example.com",
    dob: "Nov 03, 1995 (28 years)",
    address: "789 Pine Road\nManhattan, NY 10019",
    lastVisit: "Mar 10, 2024",
    nextAppt: "Apr 05, 2024",
    status: "Active",
    avatar: "SC",
    color: "from-amber-500 to-orange-500",
    visits: 15,
    registeredSince: "Sep 2022",
    outstanding: "$0",
    lastXRay: "Mar 2024",
    insurance: "Aetna",
    allergies: [
      { name: "Sulfa drugs", severity: "warning" },
    ],
    conditions: [],
    medications: [],
    visitHistory: [
      { date: "Mar 10, 2024", treatment: "Orthodontic Adjustment", doctor: "Dr. Lee", notes: "Adjusted wire on upper arch. Patient reported minor discomfort. Next visit in 4 weeks.", tooth: "All" },
      { date: "Feb 10, 2024", treatment: "Orthodontic Check-up", doctor: "Dr. Lee", notes: "Braces progressing well. Good alignment improvement on anterior teeth.", tooth: "All" },
      { date: "Jan 10, 2024", treatment: "Orthodontic Adjustment", doctor: "Dr. Lee", notes: "Changed elastics. Added power chain for gap closure.", tooth: "All" },
    ],
    invoices: [],
  },
  {
    id: "P-1004",
    name: "James Rodriguez",
    phone: "+1 234-567-8903",
    email: "james.r@example.com",
    dob: "Apr 17, 1980 (44 years)",
    address: "321 Cedar Lane\nQueens, NY 11375",
    lastVisit: "Jan 05, 2024",
    nextAppt: "—",
    status: "Inactive",
    avatar: "JR",
    color: "from-gray-400 to-gray-500",
    visits: 3,
    registeredSince: "Oct 2023",
    outstanding: "$2,500",
    lastXRay: "Dec 2023",
    insurance: "None",
    allergies: [],
    conditions: [
      { name: "Heart Murmur", diagnosed: "2015", status: "Monitoring", statusColor: "bg-amber-50 text-amber-700 border-amber-200" },
    ],
    medications: [
      { name: "Aspirin 81mg", dosage: "1 tablet daily (Heart)", color: "bg-red-50 text-red-600" },
    ],
    visitHistory: [
      { date: "Jan 05, 2024", treatment: "Dental Implant Consultation", doctor: "Dr. Adams", notes: "Patient interested in implant for tooth #19. Discussed treatment plan and costs.", tooth: "#19" },
      { date: "Dec 10, 2023", treatment: "Extraction", doctor: "Dr. Smith", notes: "Extracted severely decayed tooth #19. Post-op instructions given.", tooth: "#19" },
    ],
    invoices: [
      { id: "INV-2024-004", date: "Jan 05, 2024", amount: "$2,500.00", status: "Overdue", treatment: "Dental Implant Consultation" },
    ],
  },
  {
    id: "P-1005",
    name: "Aisha Patel",
    phone: "+1 234-567-8904",
    email: "aisha.p@example.com",
    dob: "Aug 29, 1990 (33 years)",
    address: "654 Birch Blvd, Unit 8B\nBronx, NY 10458",
    lastVisit: "Mar 22, 2024",
    nextAppt: "Mar 30, 2024",
    status: "Active",
    avatar: "AP",
    color: "from-emerald-500 to-teal-500",
    visits: 20,
    registeredSince: "May 2022",
    outstanding: "$180",
    lastXRay: "Mar 2024",
    insurance: "MetLife",
    allergies: [
      { name: "Ibuprofen", severity: "warning" },
      { name: "Shellfish", severity: "outline" },
    ],
    conditions: [],
    medications: [],
    visitHistory: [
      { date: "Mar 22, 2024", treatment: "Teeth Whitening Session", doctor: "Dr. Lee", notes: "In-office whitening completed. Patient achieved 4-shade improvement. Advised to avoid staining foods for 48 hours.", tooth: "All" },
      { date: "Mar 01, 2024", treatment: "Routine Cleaning", doctor: "Dr. Adams", notes: "Standard prophylaxis. Gum health good. Minor calculus removed.", tooth: "All" },
    ],
    invoices: [
      { id: "INV-2024-005", date: "Mar 22, 2024", amount: "$180.00", status: "Due in 7 days", treatment: "Teeth Whitening Session" },
    ],
  },
  {
    id: "P-1006",
    name: "David Kim",
    phone: "+1 234-567-8905",
    email: "david.k@example.com",
    dob: "Feb 14, 1997 (27 years)",
    address: "987 Maple Drive\nStaten Island, NY 10301",
    lastVisit: "Mar 25, 2024",
    nextAppt: "Apr 02, 2024",
    status: "Active",
    avatar: "DK",
    color: "from-indigo-500 to-violet-500",
    visits: 6,
    registeredSince: "Nov 2023",
    outstanding: "$0",
    lastXRay: "Mar 2024",
    insurance: "Guardian",
    allergies: [],
    conditions: [],
    medications: [],
    visitHistory: [
      { date: "Mar 25, 2024", treatment: "Composite Filling", doctor: "Dr. Smith", notes: "Filled cavity on tooth #30 with composite resin. Bite adjusted. Patient advised to avoid hard foods for 24 hours.", tooth: "#30" },
      { date: "Mar 05, 2024", treatment: "Dental Examination", doctor: "Dr. Adams", notes: "Routine exam. Found small cavity on #30. Scheduled filling.", tooth: "#30" },
    ],
    invoices: [],
  },
];

export type PatientData = typeof patientsData[number];

export function getPatientById(id: string): PatientData | undefined {
  return patientsData.find((p) => p.id === id);
}
