'use server'
/**
 * invitations.ts — Staff Invite Flow Server Actions
 *
 * Uses the Invitation model (@@map("invitations")) which is the lighter-weight
 * invitation model with DB-generated token. For the heavier StaffInvitation
 * flow (with hashed token, fullName, jobTitle), see src/app/actions/auth.ts
 * → createStaffInvitation() + acceptStaffInvitation().
 *
 * Prisma models used:
 *   Invitation  (@@map("invitations"))
 *     id, tenantId, email, role, token (auto-generated hex), invitedBy (UUID?),
 *     expiresAt, acceptedAt, createdAt
 *     relation: tenant (Tenant)
 *
 *   User        (@@map("users"))
 *     id, supabaseId, email
 *
 *   TenantMembership (@@map("tenant_memberships"))
 */
import { withPermission } from '@/lib/rbac/guard'
import { getUserSession } from '@/lib/rbac/session'
import { rawPrisma } from '@/lib/prisma'
import { Resend } from 'resend'

// Resend client — only instantiated if API key is set
const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null

/** Send (or log) an invitation email */
async function sendInvitationEmail(opts: {
  to:         string
  clinicName: string
  role:       string
  inviteUrl:  string
}) {
  const subject = `You're invited to join ${opts.clinicName}`
  const html = `
    <div dir="ltr" style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0a0a0f; color: #fff; padding: 40px; border-radius: 16px;">
      <h2 style="color: #60a5fa; margin-bottom: 8px;">You've Been Invited!</h2>
      <p style="color: #aaa; margin-bottom: 24px;">
        You've been invited to join <strong style="color: #fff;">${opts.clinicName}</strong>
        as a <strong style="color: #fff;">${opts.role}</strong>.
      </p>
      <a href="${opts.inviteUrl}"
         style="display: inline-block; background: #2563eb; color: #fff; padding: 14px 28px;
                border-radius: 8px; text-decoration: none; font-weight: bold; margin-bottom: 24px;">
        Accept Invitation
      </a>
      <p style="color: #555; font-size: 13px;">This invitation expires in 7 days.</p>
    </div>
  `

  if (resend) {
    await resend.emails.send({
      from:    'Neoliva <noreply@neoliva.app>',
      to:      opts.to,
      subject,
      html,
    })
  } else {
    // Dev fallback — log instead of sending
    console.log(`[Invitation Email — DEV FALLBACK]`)
    console.log(`  To:      ${opts.to}`)
    console.log(`  Subject: ${subject}`)
    console.log(`  URL:     ${opts.inviteUrl}`)
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// PUBLIC ACTIONS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Invite a staff member by email.
 * Requires 'staff' + 'create' permission.
 * OWNER role is required to invite another OWNER.
 *
 * Creates an Invitation record using Prisma's DB-generated token, then sends
 * a link to /invite/[token].
 */
export async function inviteStaff(data: {
  email: string
  role:  string
  name:  string   // display name used in the invitation email
}) {
  return withPermission('staff', 'create', async (session) => {
    // Only owners may invite other owners
    if (data.role === 'OWNER' && session.role !== 'OWNER') {
      throw new Error('Only owners can invite other owners')
    }

    // Check for an already-pending, non-expired invitation for this email+tenant
    const existing = await rawPrisma.invitation.findFirst({
      where: {
        tenantId:   session.tenantId,
        email:      data.email,
        acceptedAt: null,
        expiresAt:  { gt: new Date() },
      },
    })
    if (existing) throw new Error('An active invitation already exists for this email address')

    const expiresAt = new Date()
    expiresAt.setDate(expiresAt.getDate() + 7)

    // Fetch the tenant name for the email
    const tenant = await rawPrisma.tenant.findUnique({
      where:  { id: session.tenantId },
      select: { name: true },
    })

    // Create invitation — token is auto-generated by DB (gen_random_bytes)
    const invitation = await rawPrisma.invitation.create({
      data: {
        tenantId:  session.tenantId,
        email:     data.email,
        role:      data.role,
        invitedBy: session.dbUserId,   // internal DB user id (not Supabase UUID)
        expiresAt,
      },
      select: { id: true, token: true },
    })

    const appUrl    = process.env.NEXT_PUBLIC_APP_URL ?? process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'
    const inviteUrl = `${appUrl}/invite/${invitation.token}`

    await sendInvitationEmail({
      to:         data.email,
      clinicName: tenant?.name ?? 'Your Clinic',
      role:       data.role,
      inviteUrl,
    })

    return { success: true, invitationId: invitation.id }
  })
}

/**
 * Look up an invitation by its token. Public — no auth required.
 *
 * Returns the details needed to render the invitation acceptance page.
 * Throws if the token is invalid, expired, or already accepted.
 */
export async function getInvitationByToken(token: string) {
  const invitation = await rawPrisma.invitation.findFirst({
    where: {
      token,
      acceptedAt: null,
      expiresAt:  { gt: new Date() },
    },
    select: {
      id:        true,
      email:     true,
      role:      true,
      expiresAt: true,
      tenant:    { select: { name: true } },
    },
  })

  if (!invitation) throw new Error('Invalid or expired invitation')

  return {
    id:         invitation.id,
    email:      invitation.email,
    role:       invitation.role,
    expiresAt:  invitation.expiresAt,
    tenantName: invitation.tenant.name,
    token,
  }
}

/**
 * Complete the invitation acceptance flow for an already-authenticated user.
 *
 * Called after the user has signed in / signed up. Creates the TenantMembership
 * and marks the invitation as accepted.
 *
 * @param token      - Raw invitation token from the URL
 * @param supabaseId - The Supabase auth user id of the accepting user
 */
export async function completeInvitation(token: string, supabaseId: string) {
  // Re-validate the token
  const invitation = await rawPrisma.invitation.findFirst({
    where: { token, acceptedAt: null, expiresAt: { gt: new Date() } },
    select: { id: true, tenantId: true, role: true, email: true },
  })
  if (!invitation) throw new Error('Invalid or expired invitation')

  // Resolve internal DB user from Supabase auth id
  const dbUser = await rawPrisma.user.findUnique({
    where:  { supabaseId },
    select: { id: true },
  })
  if (!dbUser) throw new Error('User account not found — please sign up first')

  // Ensure no duplicate membership
  const existingMembership = await rawPrisma.tenantMembership.findUnique({
    where: { userId_tenantId: { userId: dbUser.id, tenantId: invitation.tenantId } },
  })
  if (existingMembership) {
    // Already a member — just mark invitation accepted and return
    await rawPrisma.invitation.update({
      where: { id: invitation.id },
      data:  { acceptedAt: new Date() },
    })
    return { tenantId: invitation.tenantId, role: invitation.role }
  }

  // Create membership + mark invitation accepted in a transaction
  await rawPrisma.$transaction([
    rawPrisma.tenantMembership.create({
      data: {
        tenantId: invitation.tenantId,
        userId:   dbUser.id,
        role:     invitation.role as any,
        status:   'ACTIVE',
        isActive: true,
      },
    }),
    rawPrisma.invitation.update({
      where: { id: invitation.id },
      data:  { acceptedAt: new Date() },
    }),
  ])

  return { tenantId: invitation.tenantId, role: invitation.role }
}
